# Generated by Django 4.2.23 on 2025-08-02 07:20

import casestudy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='casestudyimage',
            field=models.ImageField(blank=True, help_text='Upload an image for this case study. Image will be saved with the case study slug as filename.', null=True, upload_to=casestudy.models.casestudy_image_path),
        ),
    ]
