# Generated by Django 4.2.23 on 2025-08-05 15:22

import casestudy.models
import casestudy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_casestudy_casestudyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['title'], 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='casestudyimage',
            field=models.ImageField(blank=True, help_text='Upload an image for this case study. Image will be saved to static directory for Heroku compatibility.', null=True, storage=casestudy.storage.StaticImageStorage(), upload_to=casestudy.models.casestudy_image_path),
        ),
    ]
