# Generated by Django 4.2.23 on 2025-08-06 05:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0004_change_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='casestudyimage',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
